


#ifndef ULTRASONIC_CFG_H_
#define ULTRASONIC_CFG_H_

#define ULTRASONIC_ICU_POWER_PORT C
#define ULTRASONIC_ICU_POWER_PIN PIN0


#define ULTRASONIC_INT0_POWER_PORT C
#define ULTRASONIC_INT0_POWER_PIN PIN1


#define ULTRASONIC_INT1_POWER_PORT C
#define ULTRASONIC_INT1_POWER_PIN PIN2



#endif  /*ULTRASONIC_CFG_H_*/

